flyway.url=jdbc:postgresql://localhost:5432/pulse
flyway.user=pulse
flyway.password=pulse
flyway.defaultSchema=flyway
flyway.schemas=flyway,epok,studentits,ladok
flyway.locations=classpath:db/migration/epok,classpath:db/migration/studentits,classpath:db/migration/ladok
flyway.baselineOnMigrate=true
flyway.cleanDisabled=false

