-- Create the Ladok schema
CREATE SCHEMA IF NOT EXISTS ladok;

-- Create the Result table with proper IDENTITY column
CREATE TABLE IF NOT EXISTS ladok.result (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(50) NOT NULL,
    student_id VARCHAR(50) NOT NULL,
    grade VARCHAR(10) NOT NULL,
    date_reported DATE NOT NULL
);
